// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6q3rx9QQViT5At1Ll8blhBnniaVivKBo',
    appId: '1:481814121665:web:2dc225d3c6816733069840',
    messagingSenderId: '481814121665',
    projectId: 'zee-palm-flutter',
    authDomain: 'zee-palm-flutter.firebaseapp.com',
    storageBucket: 'zee-palm-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2EJkXTe89Oo79c_o3IhAPludP2Zw5NBg',
    appId: '1:481814121665:android:917b9b6e42d60eff069840',
    messagingSenderId: '481814121665',
    projectId: 'zee-palm-flutter',
    storageBucket: 'zee-palm-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNk30IjQDaTBGhsITQntoVNRLeMSetsHA',
    appId: '1:481814121665:ios:24808b6923ecb189069840',
    messagingSenderId: '481814121665',
    projectId: 'zee-palm-flutter',
    storageBucket: 'zee-palm-flutter.firebasestorage.app',
    iosBundleId: 'com.example.zeepalmAssessment',
  );
}
